channels:
- conda-forge
- nodefaults
dependencies:
# applications
- jupyterlab=4.0
- nbconvert=7
- pip
- pip:
  - notebook=7.0.0b3
  - jupyter-collaboration
# Lab Extensions
- jupyterlab-fasta=3.3
- jupyterlab-geojson=3.4
# - jupyter-offlinenotebook - still depends on `notebook`
# Python Kernel
- ipykernel
- xeus-python
# Extensions
- ipywidgets
- widgetsnbextension
- ipyleaflet
- altair
- bqplot
- dask
- matplotlib-base
- pandas=2
- python=3.10
- scikit-image
- scikit-learn
- seaborn
- tensorflow
- sympy
- pyyaml
- traittypes==0.2.1
- invoke
# C++ Kernel
#- xeus-cling=0.10
#- xtensor=0.20.8
#- xtensor-blas=0.16.1
#- xwidgets=0.24.2
#- xleaflet=0.13.1
# CLI tools
- vim
