channels:
- conda-forge
- nodefaults
# applications
- jupyterlab=4.0
- notebook=7.0.0b3
- nbconvert=7
# Lab Extensions
- jupyter-offlinenotebook=0.2
- jupyterlab-fasta=3.1
- jupyterlab-geojson=3.1
- jupyterlab-link-share=0.2
# RTC
- jupyterlab-collaboration
# Python Kernel
- ipykernel
- xeus-python
# Extensions
- ipywidgets=7.6
- widgetsnbextension=3.5
- ipyleaflet=0.13
- altair=4.1
- bqplot=0.12.20
- dask=2020.12
- matplotlib-base=3.1
- pandas=1
- python=3.8
- scikit-image
- scikit-learn
- seaborn
- tensorflow
- sympy=1.4
- pyyaml
- traittypes==0.2.1
- invoke=1.2
# C++ Kernel
- xeus-cling=0.10
- xtensor=0.20.8
- xtensor-blas=0.16.1
- xwidgets=0.24.2
- xleaflet=0.13.1
# CLI tools
- vim
